# CHI-SQUARE TEST

### Step 1 : Import Libraries

In [24]:
import numpy as np
from scipy.stats import chi2

### Step 2: Row sums, column sums, and total

In [27]:
row_totals = observed.sum(axis=1)
col_totals = observed.sum(axis=0)
grand_total = observed.sum()
row_totals,col_totals,grand_total

(array([120, 180, 150,  80,  70]), array([240, 360]), np.int64(600))

### Step 3: Observed frequency table

In [35]:
observed = np.array([[50, 70],[80, 100], [60, 90],[30, 50],[20, 50]])
observed

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

### Step 4: Expected frequency table

In [28]:
expected = np.outer(row_totals, col_totals) / grand_total
expected

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

### Step 5: Chi-Square Statistic

In [29]:
chi_square_stat = ((observed - expected) ** 2 / expected).sum()
chi_square_stat

np.float64(5.638227513227513)

### Step 6: Degrees of Freedom

In [30]:
rows, cols = observed.shape
df = (rows - 1) * (cols - 1)
df

4

### Step 7: Critical Value for alpha = 0.05

In [31]:
alpha = 0.05
critical_value = chi2.ppf(1 - alpha, df)
critical_value

np.float64(9.487729036781154)

### Step 8: Decision

In [34]:
if chi_square_stat > critical_value:
    decision = "Reject the null hypothesis (significant association)."
else:
    decision = "Fail to reject the null hypothesis (no significant association)."
print("Conclusion:", decision)

Conclusion: Fail to reject the null hypothesis (no significant association).
